data:
  data_dir: data/objects/
  dataset: PUNet
  augment: true
  use_rgb_features: false
  workers: 4
  npoints: 2048
diffusion:
  timesteps: 1000
  sampling_timesteps: 10
  objective: pred_noise
  schedule: linear
  sampling_strategy: DDPM
  loss_type: mse
  beta_start: 0.0001
  beta_end: 0.04
  t0: 0.0001
  T: 1.0
  ot_ode: true
model:
  type: Hash_Encoding_Transformer
  ema: true
  in_dim: 3
  extra_feature_channels: 0
  out_dim: 3
  time_embed_dim: 64
  dropout: 0.15
  EMA:
    decay: 0.999
  PVD:
    use_global_embedding: false
    global_embedding_dim: 1024
    feat_embed_dim: 64
    transformer_heads: 16
    transformer_layers: 8
    transformer_ffn_dim: 256
    out_mlp: 128
sampling:
  bs: 32
  num_iter: 8
training:
  optimizer:
    type: AdamW
    lr: 0.0003
    beta1: 0.9
    beta2: 0.999
    weight_decay: 1.0e-05
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: true
    value: 1.0
  bs: 16
  overfit: false
  amp: true
  steps: 200000
  accumulation_steps: 1
  log_interval: 10
  save_interval: 20000
  viz_interval: 5000
  seed: 42
  max_epochs: 1000
